/**
 * File generated by Magnet rest2mobile 1.1 - Jul 2, 2015 10:54:13 PM
 * @see {@link http://developer.magnet.com}
 */

package cos.loginfunctionality.model.beans;


/**
 * Generated from json example
{
  "username" : "username",
  "password" : "password"
}

 */

public class LoginDataResult {

  
  private String password;

  
  private String username;

  public String getPassword() {
    return password;
  }
  public String getUsername() {
    return username;
  }

  /**
  * Builder for LoginDataResult
  **/
  public static class LoginDataResultBuilder {
    private LoginDataResult toBuild = new LoginDataResult();

    public LoginDataResultBuilder() {
    }

    public LoginDataResult build() {
      return toBuild;
    }

    public LoginDataResultBuilder password(String value) {
      toBuild.password = value;
      return this;
    }
    public LoginDataResultBuilder username(String value) {
      toBuild.username = value;
      return this;
    }
  }
}
