/**
 * File generated by Magnet rest2mobile 1.1 - Jul 2, 2015 10:54:13 PM
 * @see {@link http://developer.magnet.com}
 */

package cos.loginfunctionality.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import cos.loginfunctionality.model.beans.*;

public class LoginDataFactory extends ControllerFactory<LoginData> {
  public LoginDataFactory(MagnetMobileClient magnetClient) {
    super(LoginData.class, LoginDataSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller LoginData
  public static class LoginDataSchemaFactory extends AbstractControllerSchemaFactory {
    private static LoginDataSchemaFactory __instance;

    public static synchronized LoginDataSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new LoginDataSchemaFactory();
      }

      return __instance;
    }

    private LoginDataSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getLoginData
      JMethod method1 = addMethod("getLoginData",
        "OnlyRugby/users/",
        "GET",
        LoginDataResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("https://localhost");
    }

  }

}
