/**
 * File generated by Magnet rest2mobile 1.1 - Jul 2, 2015 10:54:13 PM
 * @see {@link http://developer.magnet.com}
 */

package cos.loginfunctionality.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import cos.loginfunctionality.model.beans.*;

public interface LoginData {

  /**
   * Generated from URL GET https://localhost/OnlyRugby/users/
   * GET OnlyRugby/users/
   * @param listener
   * @return LoginDataResult
   */
  Call<LoginDataResult> getLoginData(StateChangedListener listener);
}
